### ISSUE TITLE
[BUG] Once karma reaches negatives you stop being able to gain coins

### ISSUE THREAD

**Issue by Neceros** [hodldeeznuts/twitchtoolkit#13]
1. What was expected to happen?
I figured the negative karma would stop at 1% and earn minuscule coins.

2. What actually happened?
Negative karma went as low as -270%, meaning they can never again earn coins nor karma.

**Comment by hodlhodl1132** [comment]
This isn't a bug. You can prevent viewers from going negative in karma settings.

**Comment by hodlhodl1132** [comment]
As a side note, I have added the option to set the lowest karma viewers can get to.

**Comment by nappelinis** [comment]
I see this being closed, but I think it might have to be revisited. For the avg streamer this isn't clear that negative karma will create issues on karma/coin gain. Attaching a link with some math on how this affects Viewers the least. And Mods, VIP, Subs even more!
https://docs.google.com/spreadsheets/d/1KujTlz9d7Cw7s1yoIlvv8Wm-Vaovc2IJzx3tM45feF0/edit#gid=0

My suggestion would be to simply put in a NOTE saying: If you set karma to be allowed negative or zero, this will cause possible issues.
