### ISSUE TITLE
[BUG] When there's no event options to choose from the window never disappears

### ISSUE THREAD

**Issue by Neceros** [hodldeeznuts/twitchtoolkit#14]
1. What was expected to happen?
Not sure. 

2. What actually happened?

It gave chat an event vote option, but there were no options to choose from. The bar never started to countdown. Also, coins and karma stopped ticking. Restarting the game fixed it.

3. What could have caused this? (optional but helpful)

We were in a very frozen wasteland. Not sure if maybe there just were no events possible or what

**Comment by hodlhodl1132** [comment]
Do you know which storyteller this was from? I know this was possible with the HodlBot (Green) votes, which I have fixed.

**Comment by Neceros** [comment]
Yes it was Hodl.

**Comment by hodlhodl1132** [comment]
Ok that bug was fixed then.
