### ISSUE TITLE
[REQUEST] Bad events cost less as the game goes on

### ISSUE THREAD

**Issue by Neceros** [hodldeeznuts/twitchtoolkit#17]
1. How does your idea work?
The longer a game goes on the easier it should be for viewers to buy bad events. After a certain amount of pawns reached and time passed.

2. How is this different from what already exists?

3. Why is this needed? What problem does this solve?
Would make ending the colony easier but only after a certain time. We only use 375% max karma so chat doesn't get too crazy too early.

**Comment by hodlhodl1132** [comment]
Many of the bad events use coin wagers to make a proportionally sized threat. The ones that don't are going to be at some point. The idea of a higher max karma is to let viewers more easily afford bad events. I would suggest possibly re-balancing your settings or reevaluating the costs to the events. The goal of the mod isn't to end the colony.
