### ISSUE TITLE
Prisoner event [BUG]

### ISSUE THREAD

**Issue by sirphilth** [hodldeeznuts/twitchtoolkit#20]
1. What was expected to happen?
A prisoner would be spawned in, taking away the cost of the event and adding karma for event

2. What actually happened?
A prisoner spawned, not taking away the cost of the event and not adding karma for event

3. What could have caused this? (optional but helpful)
No comment

4. Additional info
We have tried the event 3 times, with the same outcome everytime. Did not reload save or game in between.

**Comment by hodlhodl1132** [comment]
Fixed in next update. Thank you :)
