### ISSUE TITLE
[BUG]randomdisease

### ISSUE THREAD

**Issue by sirphilth** [hodldeeznuts/twitchtoolkit#22]
1. What was expected to happen?
A random disease being bought (!buy randomdisease) with points wagered, that would affect the correct pawn type

2. What actually happened?
A random disease being bought with points wagered, that did not affect the correct pawn type. An animal disease that hit 3 colonists instead (plague)

3. What could have caused this? (optional but helpful)
No comment.

4. Additional info:
At the time the animal disease got bought, I had the following animals; 1 husky, 1 tortoise, 1 emu, 1 sheep calf, 1 mechaspider (Genetic Rim Mod), 1 White dragon (dragon mod), 1 True dragon (dragon mod). I listed the animals to clarify there were multiple (vanilla) targets for the disease to hit.

For reference; https://clips.twitch.tv/BreakableMoldyDiscPJSalt

**Comment by Codingale** [comment]
It seems the popup stated it was animals however it successfully applied the human hediff which gives debuffs to consciousness and manipulation and adds +20% pain.

I'm not quite sure why the menu showed this perhaps @hodldeeznuts would have further about how it's done in game.

**Comment by hodlhodl1132** [comment]
I see where I went wrong here. It was pulling all incident defs that had a disease included in it. I have switched to only look for incident defs with the worker class for human diseases.
