### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by apotatocat** [hodldeeznuts/twitchtoolkit#24]
1. Event to happen after votes have/have not been cast

2. No event occurred I had to reload my RimWorld save to fix it (But would stop working again after a while)

3. Mod conflict? (I have not installed any new mods, but some have updated)

**Comment by hodlhodl1132** [comment]
I'm not sure if you had a small bug that was only live for a short period but i have not experience nor seen this behavior myself. I would say try to replicate and or give more details about the specific votes that are happening.
