### ISSUE TITLE
Connection error with beta version

### ISSUE THREAD

**Issue by rshackleton** [hodldeeznuts/twitchtoolkit#3]
The game is frequently hanging and then printing this error. Confused as this seems to be using a local IP address rather than a remote IP address. Especially strange because the local IP address does not exist on my network.

```
[TwitchToolkit] http://192.168.0.20:6779?{"method":"get","username":"shackattackbot"}
Verse.Log:Message(String, Boolean)
TwitchToolkit.Helper:Log(String)
TwitchToolkit.Utilities.WebClientHelper:UploadString(String[], String, String[])
TwitchToolkit.StreamLabs:GetViewerPoints(Viewer)
TwitchToolkit.Viewer:GiveViewerCoins(Int32)
TwitchToolkit.Viewers:AwardViewersCoins(Int32)
TwitchToolkit.Ticker:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

**Comment by rshackleton** [comment]
Looks like a hardcoded value here:

https://github.com/hodldeeznuts/twitchtookit/blob/ef858b9b84bd204e28c9eda7321d796c211232af/TwitchToolkit/StreamLabs.cs#L14

**Comment by hodlhodl1132** [comment]
this is because it connects to a script in local streamlabs chat bot that hosts a local webserver at that address that syncs the coins between streamlabs currency. Just turn of streamlabs sync under integrations and it won't come up with that error. I am working on a new system for this.
