### ISSUE TITLE
[BUG] No voting events

### ISSUE THREAD

**Issue by omniodin** [hodldeeznuts/twitchtoolkit#30]
1. What was expected to happen? Events to vote for.

2. What actually happened? No events to vote for.

3. What could have caused this? (optional but helpful) Only having Hodlbot active initially then activating Cassandra on top of that? Idk it worked last night and now it doesn't.

**Comment by hodlhodl1132** [comment]
Check development mode and search for errors.

Which storyteller packs are enabled?

Which storyteller are you using?

Is this a new save or mid way through save?

**Comment by omniodin** [comment]
I'll search for errors tonight when I get off of work. I remember seeing more events errors last night when I launched the game.

I had Hodlbot activated.

Cassandra.

It happened mid save whereas it was all working the night prior.

**Comment by omniodin** [comment]
I also added the -popupwindow to my launch options so idk if that would have anything to do with it.

**Comment by hodlhodl1132** [comment]
That would have nothing to do with it.

**Comment by omniodin** [comment]
https://gist.github.com/HugsLibRecordKeeper/119a1f804c777022f29b8f54120dcccb

Here are is the debug log associated with tonight. I'm still not getting any events.

**Comment by hodlhodl1132** [comment]
There are no visible errors. It helps a lot more to have development mode, debug log with auto-open on so you can activiely look for red errors.

Maybe you could also try disabling in-game def editor.

**Comment by omniodin** [comment]
Ill have debug on tonight while I stream so I can actively catch errors.

**Comment by omniodin** [comment]
I'm not sure if it's a cooldown thing or what but I did get exactly one event tonight. I never got any errors associated with the Twitch Toolkit though, so I don't know what the deal is.

**Comment by omniodin** [comment]
https://www.dropbox.com/s/qncbrf1lyo5eee1/People%27s%20Isolation%20Union%20%28Permadeath%29.rws?dl=0
 My save game for you to peruse.

**Comment by hodlhodl1132** [comment]
I take it back, I have no interest in trying to debug this mess. Hopefully your issues can be solved through smaller saves.

**Comment by omniodin** [comment]
lmao I don't blame you.
