### ISSUE TITLE
[REQUEST] Configuration Options for How Votes are Displayed

### ISSUE THREAD

**Issue by elPerstin** [hodldeeznuts/twitchtoolkit#31]
1. What was expected to happen?
A vote started, for colonist events.

2. What actually happened?
Three options were given: Colonist, Colonist, Colonist

3. What could have caused this? (optional but helpful)
https://gist.github.com/8941e550ccc7a75d92960e6c4769a95f
![123](https://user-images.githubusercontent.com/1962479/59490487-1f64b900-8e85-11e9-8cd6-2fd93174835c.png)

**Comment by hodlhodl1132** [comment]
I don't know how to deal with this. It's actually not a bug....

**Comment by hodlhodl1132** [comment]
Now a Feature-Request.
