### ISSUE TITLE
[REQUEST] Options to Configure Coin Reward toggle to not disable store related commands

### ISSUE THREAD

**Issue by KevinBlacher** [hodldeeznuts/twitchtoolkit#33]
1. What was expected to happen?
!purchaselist, !buy ticket, and !bal should work while this option is off.

2. What actually happened?
The commands do not get read by the mod while the option "reward viewers set coin amount per interval" is off.

3. What could have caused this? (optional but helpful)

**Comment by hodlhodl1132** [comment]
It was intended this way. So if a streamer chose to disable coin store, it shouldn't be showing purchase list or bal. I can't check right now but I'm pretty sure !buy ticket should still work

**Comment by KevinBlacher** [comment]
To specify further, I am saying it does not allow those commands when the option to reward viewers with coins automatically is off. During the time when these commands were not working, I had "Allow viewers to purchase items/events" toggled on.

**Comment by hodlhodl1132** [comment]
I am so aware of this because it was 100% intentional. No need to further specify anything. I did not predict a situation where the store would be on but coin rewards would be off.
