### ISSUE TITLE
[BUG] IncidentHelpers that send letters in IsPossible method desync the viewer messages

### ISSUE THREAD

**Issue by sirphilth** [hodldeeznuts/twitchtoolkit#34]
1. What was expected to happen?
Buyevent inspiration, which would give inspiration to colonists

2. What actually happened?
Buyevent inspiration, which gives inspiration to colonists. The inspiration DID get bought But it desyncd the "correct names" of following bought items.

3. What could have caused this? (optional but helpful)

**Comment by hodlhodl1132** [comment]
Please elaborate, I do not understand. How can I recreate?

**Comment by sirphilth** [comment]
Correct me if I'm wrong, but I thought I read somewhere you wanted to know which events cause a desync. Thats why I noted this one, I would not know how to recreate it.
 So if this is of no help, my apologies and close this bugpost.

**Comment by hodlhodl1132** [comment]
What do you mean by desync?

**Comment by sirphilth** [comment]
Person A buys the inspiration. Then Person B buys something. The item Person B buys has the name and message of Person A in the box. Then person C buys something and Person B's name an message is in the box.

I think it's because certain events have no name & message attached to them so they all shift up by one

If you meant other desyncs, please elaborate what I need to look out for (perhaps on discord, or if it's already on discord I'll see if I can find it). and I'll note it down in the future

**Comment by hodldeeznuts** [comment]
Inspiration should cause a message to appear, is it possible it was actually the one before inspiration that did that. I know that torytalkervotes, hodlbotes are two that definitely do it. I don't see why inpsiration would be bugged as it has a normal letter.

**Comment by hodlhodl1132** [comment]
Ahh I see where it happens now, because the letter is called before it's executed as an incident. This needs to be changed into a variable event so it can decide when to do this on it's own.
