### ISSUE TITLE
[BUG] VotingIncident FarmAnimalsWandersIn has the wrong letter message

### ISSUE THREAD

**Issue by sirphilth** [hodldeeznuts/twitchtoolkit#35]
1. What was expected to happen?
Chat voted for farm animals wander in, and farm animals would wander in.

2. What actually happened?
Chat voted for farm animals wander in and farm animals did indeed wander in. The little box on the right side (that display what has been bought) said; "chatlabels" farm animals wander in.

3. What could have caused this? (optional but helpful)

**Comment by hodlhodl1132** [comment]
I wonder if I fixed this cause I just tested it and it was normal, maybe  I didn't push the fix yet.
