### ISSUE TITLE
[BUG] Walls can be bought

### ISSUE THREAD

**Issue by sirphilth** [hodldeeznuts/twitchtoolkit#36]
1. What was expected to happen?
Walls (smoothed granite/marble/slate) can be bought. 

2. What actually happened?
Walls (smoothed granite/marble/slate) get bought and they get spawned in as actual walls. Now this isn't a big problem, usually I disable events like this, but you can't find this "item" in the list. It cannot be disabled. That is the big issue.

3. What could have caused this? (optional but helpful)
My guess it's because walls have the [item] label. OR it has something to do with the minify everything mod. Allthough I don't think you can "minify" (Minify mod lets you "uninstal/reinstal" MOST buildable items. from batteries to bedrolls to geothermal generators.) smoothed walls.

**Comment by hodlhodl1132** [comment]
I'm not sure this is something I can solve since it does have to do with minifying items. The store considers any item that can be re-installed as buyable.

**Comment by hodlhodl1132** [comment]
This isn't something I can solve, you are better off manually disabling them. If i were to fix this i would create items that wouldn't show up in the item list anymore that really should be there such as chairs and tables, and i think that would be a lesser tradeoff than having to disable some things or just not have the minify everything mod.

**Comment by sirphilth** [comment]
Thats the actual issue, you can't disable them. If that was an option I would've not opened this post. But if nothing can be done I will just issue out a warning of removing coins/karma if anyone deliberatly buys them.

**Comment by hodlhodl1132** [comment]
Gotcha, I'll have to test this out. Will re-open for now then

**Comment by sirphilth** [comment]
Alright I've tested this out in toolkit stream who did not have the minify mod. It got purchased anyways. So it's not a minify mod issue.

**Comment by hodlhodl1132** [comment]
There are two instances where items are pulled from the DefDatabase to be chosen as a buyable item. This small difference made it so walls wouldn't make it to the store list but would still be in the StoreInventory/
