### ISSUE TITLE
!toolkitcmds [Minor issue]

### ISSUE THREAD

**Issue by sirphilth** [hodldeeznuts/twitchtoolkit#37]
I'm going to deviate from the normal bug posting here (pls hodl no kill me). 
I am pretty sure this must be on your list already, but my viewers keep bringing it to my attention.

Now I am not sure if I can change this myself (without going into the code myself). But the original command list is outdated: "You can use the following commands: !bal, !buyevent, !buyitem, !instructions, !purchaselist, !modinfo, !modsettings, !whatiskarma, !giftcoins"

Again, this is absolutely a MINOR issue. But atleast now it has been written down and can be organized with the other "to do" maybe.

**Comment by hodlhodl1132** [comment]
Duplicate issue
