### ISSUE TITLE
[BUG] No Chat connectivity after one line

### ISSUE THREAD

**Issue by elPerstin** [hodldeeznuts/twitchtoolkit#38]
1. What was expected to happen?
Mod should respond to commands.
![after_toolkit_update](https://user-images.githubusercontent.com/1962479/59552995-021c1180-8f8f-11e9-97e2-578a823dcbf6.png)

2. What actually happened?
After one line in the chat, mod doesn't update chat in toolkit-chatwindow. no commands are recognised.
3. What could have caused this? (optional but helpful)
https://gist.github.com/8b0704339bdfbac01500d97e2065ad2b

**Comment by hodlhodl1132** [comment]
Do you have mods installed? Is this a new colony or mid save?

**Comment by elPerstin** [comment]
have a hole bunch of mods installed. it's on mid save and new colony.

Mods:
Version: 2.0.10, Mods: Core, TwitchToolkit, HugsLib, Hospitality, EdB Prepare Carefully, Infused, More Events Mod, Toolkit - More Events, More Faction Interaction, Toolkit - More Faction Interaction, Sometimes Raids Go Wrong, Raids Go Wrong - Toolkit Extension
More Trade Ships, Rimsenal, Rimsenal - Security pack, Rimsenal - Feral, Rimsenal - Federation, Rimsenal - Enhanced Vanilla Pack, Pharmacist, P-Music, Heat Map, Replace Stuff, Increased Stack, Expanded Prosthetics and Organ Engineering, Misc. Robots, Misc. Robots++
Mass Graves, Wall Light, Misc. Training, Mod Manager, RimHUD, Toolkit - Lootboxes

I don't have changed anything in the installed mods for days, so maybe it was an update, but after toolkit was updated also, i thought it might be an issue with the update

**Comment by hodlhodl1132** [comment]
I bet it's one of the Toolkit extensions. As far as I am concerned, unless a bug report is posted there are no bugs regarding other streamers.

**Comment by elPerstin** [comment]
You're totally right. Lootboxes it is. :-)
