### ISSUE TITLE
[BUG] Buying Parties can sometimes crash

### ISSUE THREAD

**Issue by crazymanatuca** [hodldeeznuts/twitchtoolkit#39]
1. What was expected to happen?
- Raids and parties bought by the viewer should be reflected in the game.

2. What actually happened? 
- The Toolkit crashes and I have to Reconnect it so the other commands will work.

3. What could have caused this? (optional but helpful)
- I thought maybe I had a mod conflict, but no matter how many or little (I started a vanilla game with just the toolkit and same thing happened) mods I use, those 2 commands crash the toolkit.

**Comment by hodlhodl1132** [comment]
There may be something wrong with your settings, try resetting all incidents. Raids do work in the vanilla game.

**Comment by hodlhodl1132** [comment]
I have just confirmed party does work as well. I will keep this open for people to submit more details but I am closing the raid portion of the issue. I already have an issue for raids but like I said probably something else cause it does work 100% of the time for me in vanilla.

**Comment by crazymanatuca** [comment]
Dangit, my fault. Somehow, the "Sometimes Raids Go Wrong" Mod got removed
from my mod list. I went back and re-installed it and everything works fine
now. Thanks for your help. I love this toolkit. It is what attracted most
of my viewers and got me to affiliate.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
