### ISSUE TITLE
[BUG]Buying a raid can crash a game

### ISSUE THREAD

**Issue by hodlhodl1132** [hodldeeznuts/twitchtoolkit#5]
1. Purchasing a raid should make a fair sized random raid to fight
2. Sometimes the raid comes and other times the game lags out, crashes, or never spawns the raid
3. High wealth and late game seem to be the biggest factors

**Comment by hodldeeznuts** [comment]
I think it's most likely that raids are crashing due to mods. I have been unable to recreate the common crash using near vanilla playthroughs. I would appreciate some people to send me save games / mod lists where raids are commonly crashing. This would definitely help me figure the issue out.

**Comment by swemoney** [comment]
I was also having this issue and was able to resolve it by disabling the `TwitchToolkit - Raids Go Wrong` mod. I'm still able to use the `Sometimes Raids Go Wrong` mod, but the TwitchToolkit addon for it appears to be causing some issues.
