### ISSUE TITLE
Reassign colonist[REQUEST]

### ISSUE THREAD

**Issue by scavmech** [hodldeeznuts/twitchtoolkit#57]
1. How does your idea work?
A button that assigns a colonist to it's current name

2. How is this different from what already exists?
Various mods break the link between viewer and pawn. This would provide an easy way to assign he pawn back to the same viewer. Right now you need to retype the viewer name over and over.

3. Why is this needed? What problem does this solve?
This would provide an easy way to assign he pawn back to the same viewer

**Comment by donavynelliott** [comment]
In the viewer assigned just manually type in a new name and it will reassign.

**Comment by hodlhodl1132** [comment]
Open the colonist assignment window and manually type in a username to reassign it.
