### ISSUE TITLE
[BUG] Raids not spawning/Locking out

### ISSUE THREAD

**Issue by VattHammer** [hodldeeznuts/twitchtoolkit#58]
1. What was expected to happen?
Spawn Raid
2. What actually happened?
Did not spawn, locks viewer out from buying anything and the toolkit chatbot crashes and needs reloading for it to work again
3. What could have caused this? (optional but helpful)
Trying to spawn raids

**Comment by hodlhodl1132** [comment]
What mods did you have?

**Comment by aquackmcquack** [comment]
I had this issue also.  However, I fixed it by removing the Toolkit Patch "Sometimes Raids go Wrong".  This would lock up the toolkit every time someone spawned a Raid (Well raid actually never spawned). I hope that helps.

**Comment by hodlhodl1132** [comment]
Bug is for Sometimes Raids go Wrong patch and not toolkit
