### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by jencey86** [hodldeeznuts/twitchtoolkit#59]
1. How does your idea work?

To have the toolkit respond to people that whisper to the user unstead of posting the response in chat to a whispered !bal or !buy

2. How is this different from what already exists?

There is a way to set up another channel to link to it, but it would keep everything in one channel instead of two

3. Why is this needed? What problem does this solve?

It would cut down on the hassle of having people have to stay in two different chat rooms, because that can get confusing. And it cuts down the spam in chat of people constantly checking balances because replies won't go there, they would go right into the whispers.

**Comment by hodlhodl1132** [comment]
Non verified accounts have a limit  to the amount of unique accounts they can whisper that is easily reached on most channels, and for that reason this feature will not happen.

**Comment by hodlhodl1132** [comment]
https://github.com/hodldeeznuts/twitchtoolkit/commit/6a060a64d3af60a8feb0c36cc5ec21bd9e1774eb
